### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rajdave69** [Rajdave69/GCR-Renamer#2]
The main things to be done-

- [x] Renaming System
- [x] Name Setting system
- [x] Renaming upon moving classes
- [x] Renaming within classes (using url of page)
- [ ] Renaming sidebar
